---
- name: Ensure apt cache is up to date
  apt:
    update_cache: yes
    upgrade: dist
  become: true

- name: Install required system packages
  apt:
    name:
      - curl
      - python3
      - python3-pip
      - ca-certificates
      - gnupg
      - lsb-release
      - zip
      - unzip
      - apt-transport-https
      - software-properties-common
    state: present
  become: true

- name: Ensure pip is upgraded
  pip:
    name: pip
    executable: pip3
    state: latest
  become: true

- name: Install Python Docker SDK and requests
  pip:
    name:
      - docker
      - requests
    executable: pip3
  become: true

- name: Download Docker installation script
  get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: '0755'
  become: true

- name: Run Docker installation script
  command: sh /tmp/get-docker.sh
  become: true

- name: Ensure Docker service is started and enabled
  service:
    name: docker
    state: started
    enabled: true
  become: true

- name: Ensure docker group exists
  group:
    name: docker
    state: present
  become: true

- name: Add current user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: true

  handlers:
    - name: Restart Docker
      service:
        name: docker
        state: restarted
      become: true
