---
# tasks file for webapp
- include_tasks: "docker-centos.yml"
  when: ansible_os_family == "CentOS"
- include_tasks: "docker-ubuntu.yml"
  when: ansible_os_family == "Ubuntu"

- name: Copy Template file
  template:
    src: "index.html.j2"
    dest: "/home/{{ ansible_user }}/index.html"

- name: Start Container
  docker_container:
    name: webapp
    image: httpd:latest
    state: started
    published_ports:
      - "80:80"
    volumes:
      - "/home/{{ ansible_user }}/index.html:/usr/local/apache2/htdocs/index.html"